CREATE STREAM IF NOT EXISTS s (t datetime64(6), k string, x float64);
CREATE STREAM IF NOT EXISTS o (x float64);
CREATE MATERIALIZED VIEW IF NOT EXISTS v INTO o AS SELECT a.x FROM s AS a LEFT JOIN s AS b ON a.k = b.k;
